In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("Employee_Performance_Dataset.csv")

In [4]:
df.head()

,Employee_ID,Age,Gender,Education,Experience,Department,City,Salary,Performance_Rating,Working_Hours,Projects,Attendance,Promotion,Purchased
0,1,22,Male,Bachelor,1,HR,Mumbai,25000,3,8,1,90,No,No
1,2,25,Female,Master,3,IT,Pune,42000,4,9,3,95,Yes,Yes
2,3,30,Male,Bachelor,6,Sales,Delhi,65000,5,9,5,97,Yes,Yes
3,4,28,Female,PhD,5,IT,Mumbai,72000,5,8,4,96,Yes,Yes
4,5,35,Male,Master,10,Finance,Pune,90000,5,10,7,98,Yes,Yes

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
nz=MinMaxScaler()

In [10]:
df[["Salary"]]=nz.fit_transform(df[["Salary"]])

In [11]:
df.head()

,Employee_ID,Age,Gender,Education,Experience,Department,City,Salary,Performance_Rating,Working_Hours,Projects,Attendance,Promotion,Purchased
0,1,22,Male,Bachelor,1,HR,Mumbai,0.007937,3,8,1,90,No,No
1,2,25,Female,Master,3,IT,Pune,0.142857,4,9,3,95,Yes,Yes
2,3,30,Male,Bachelor,6,Sales,Delhi,0.325397,5,9,5,97,Yes,Yes
3,4,28,Female,PhD,5,IT,Mumbai,0.380952,5,8,4,96,Yes,Yes
4,5,35,Male,Master,10,Finance,Pune,0.523810,5,10,7,98,Yes,Yes

In [12]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

numeric_columns = [
    "Age",
    "Experience",
    "Salary",
    "Performance_Rating",
    "Working_Hours"
]

df[numeric_columns] = scaler.fit_transform(df[numeric_columns])

print(df.head())

   Employee_ID       Age  Gender Education  Experience Department    City  \
0            1  0.041667    Male  Bachelor    0.000000         HR  Mumbai
1            2  0.166667  Female    Master    0.105263         IT    Pune
2            3  0.375000    Male  Bachelor    0.263158      Sales   Delhi
3            4  0.291667  Female       PhD    0.210526         IT  Mumbai
4            5  0.583333    Male    Master    0.473684    Finance    Pune

     Salary  Performance_Rating  Working_Hours  Projects  Attendance  \
0  0.007937            0.333333            0.0         1          90
1  0.142857            0.666667            0.5         3          95
2  0.325397            1.000000            0.5         5          97
3  0.380952            1.000000            0.0         4          96
4  0.523810            1.000000            1.0         7          98

  Promotion Purchased
0        No        No
1       Yes       Yes
2       Yes       Yes
3       Yes       Yes
4       Yes       Yes